# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EzjG15VSUtQ0r6EtU06xxSeNQ7oqr8l6
"""

!pip install streamlit
import streamlit as st
import pandas as pd
import datetime
import matplotlib.pyplot as plt

# Load the data (Replace with actual data)
@st.cache_data
def load_data():
    try:
        df = pd.read_csv("future_aluminium_prices_weekdays.csv")
        df["Date"] = pd.to_datetime(df["Date"])  # Convert date column to datetime
        return df
    except FileNotFoundError:
        return None

# Streamlit UI
st.title("📈 Aluminum Price Forecasting")
st.write("This app forecasts aluminum prices for weekdays only (Monday-Friday).")

# Load data
df = load_data()

if df is not None:
    # Show the data table
    st.subheader("📊 Forecasted Data")
    st.dataframe(df)

    # Plot the forecast
    fig, ax = plt.subplots(figsize=(10, 5))
    ax.plot(df["Date"], df["Predicted_Price"], marker="o", linestyle="dashed", color="green", label="Forecasted Price")
    ax.set_xlabel("Date")
    ax.set_ylabel("Predicted Price")
    ax.set_title("Aluminum Price Forecast for Weekdays")
    ax.legend()
    ax.grid()

    # Show plot in Streamlit
    st.pyplot(fig)
else:
    st.error("No data available. Please ensure `future_aluminium_prices_weekdays.csv` exists.")